import type { NextRequest } from "next/server";

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const format = searchParams.get("format") ?? "txt";

  const content =
    format === "json"
      ? JSON.stringify(
          {
            app: "pwcli-test-app",
            version: "0.1.0",
            generatedAt: new Date().toISOString(),
            items: Array.from({ length: 5 }, (_, i) => ({ id: i + 1, value: `item-${i + 1}` })),
          },
          null,
          2,
        )
      : `pwcli Test App Download
Generated: ${new Date().toISOString()}
Format: text

This file was generated by the pwcli test application.
It is used to test file download capabilities.

Lines of content:
${Array.from({ length: 10 }, (_, i) => `  ${i + 1}. Sample line ${i + 1}`).join("\n")}
`;

  const filename = format === "json" ? "download.json" : "download.txt";
  const contentType = format === "json" ? "application/json" : "text/plain";

  return new Response(content, {
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(Buffer.byteLength(content, "utf-8")),
    },
  });
}
