export type CommandLayer =
	| "lifecycle"
	| "observe"
	| "act"
	| "verify"
	| "diagnose"
	| "state"
	| "meta"
	| "escape";

export type Mutability = "read" | "write" | "mixed" | "escape";

export type CommandMetadata = {
	name: string;
	layer: CommandLayer;
	mutability: Mutability;
	session: "none" | "optional" | "required" | "managed";
	description: string;
	topics: string[];
};

export const commandMetadata: CommandMetadata[] = [
	{
		name: "session",
		layer: "lifecycle",
		mutability: "mixed",
		session: "none",
		description:
			"Create, attach, recreate, inspect, and close named browser sessions.",
		topics: ["session", "lifecycle", "attach", "cdp", "electron", "recovery"],
	},
	{
		name: "open",
		layer: "lifecycle",
		mutability: "write",
		session: "required",
		description: "Navigate an existing session to a URL.",
		topics: ["navigate", "url", "page"],
	},
	{
		name: "status",
		layer: "observe",
		mutability: "read",
		session: "required",
		description:
			"Inspect current page, workspace, dialogs, console/network/error summaries, and artifacts.",
		topics: ["inspect", "page", "workspace", "diagnostics"],
	},
	{
		name: "page",
		layer: "observe",
		mutability: "mixed",
		session: "required",
		description:
			"Inspect and manage pages, tabs, frames, dialogs, and page assessment state.",
		topics: ["page", "tab", "frame", "dialog"],
	},
	{
		name: "tab",
		layer: "lifecycle",
		mutability: "write",
		session: "required",
		description: "Select or close tabs by stable pageId.",
		topics: ["tab", "page", "select", "close"],
	},
	{
		name: "snapshot",
		layer: "observe",
		mutability: "read",
		session: "required",
		description:
			"Capture accessibility snapshot with optional interactive refs.",
		topics: ["snapshot", "refs", "accessibility", "inspect", "recovery"],
	},
	{
		name: "read-text",
		layer: "observe",
		mutability: "read",
		session: "required",
		description: "Read visible page text for compact understanding.",
		topics: ["text", "read", "inspect"],
	},
	{
		name: "accessibility",
		layer: "observe",
		mutability: "read",
		session: "required",
		description: "Read accessibility tree details.",
		topics: ["accessibility", "aria", "inspect"],
	},
	{
		name: "screenshot",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Capture screenshot evidence.",
		topics: ["screenshot", "evidence", "visual"],
	},
	{
		name: "pdf",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Save page as PDF evidence.",
		topics: ["pdf", "evidence", "export"],
	},
	{
		name: "click",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Click by ref, selector, or semantic locator.",
		topics: ["click", "ref", "action"],
	},
	{
		name: "fill",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Fill one input by ref, selector, or semantic locator.",
		topics: ["fill", "input", "form"],
	},
	{
		name: "type",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Type text into current focus or target element.",
		topics: ["type", "keyboard", "input"],
	},
	{
		name: "press",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Press a keyboard key.",
		topics: ["keyboard", "press", "key"],
	},
	{
		name: "hover",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Hover over an element.",
		topics: ["hover", "action"],
	},
	{
		name: "check",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Check checkbox or radio input.",
		topics: ["checkbox", "radio", "form"],
	},
	{
		name: "uncheck",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Uncheck checkbox input.",
		topics: ["checkbox", "form"],
	},
	{
		name: "select",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Select option values in a select control.",
		topics: ["select", "form", "dropdown"],
	},
	{
		name: "drag",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Drag one element to another.",
		topics: ["drag", "drop", "mouse"],
	},
	{
		name: "drop",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Drop files or MIME data onto a target element.",
		topics: ["drop", "file", "upload"],
	},
	{
		name: "upload",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Upload files through file inputs.",
		topics: ["upload", "file", "form"],
	},
	{
		name: "download",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Click target and save resulting download.",
		topics: ["download", "file", "artifact"],
	},
	{
		name: "scroll",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Scroll page or a scrollable target.",
		topics: ["scroll", "viewport"],
	},
	{
		name: "resize",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Resize current browser viewport/window.",
		topics: ["resize", "viewport", "responsive"],
	},
	{
		name: "mouse",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Perform coordinate mouse actions.",
		topics: ["mouse", "coordinate", "wheel"],
	},
	{
		name: "dialog",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Accept or dismiss native browser dialogs.",
		topics: ["dialog", "modal", "alert"],
	},
	{
		name: "wait",
		layer: "verify",
		mutability: "read",
		session: "required",
		description:
			"Wait for load, URL, text, selector, timeout, or network state.",
		topics: ["wait", "verify", "network-idle"],
	},
	{
		name: "verify",
		layer: "verify",
		mutability: "read",
		session: "required",
		description: "Assert expected text, URL, visibility, or state.",
		topics: ["verify", "assert", "check"],
	},
	{
		name: "locate",
		layer: "verify",
		mutability: "read",
		session: "required",
		description: "Locate a target and report matching state.",
		topics: ["locate", "find", "selector", "ref"],
	},
	{
		name: "get",
		layer: "verify",
		mutability: "read",
		session: "required",
		description:
			"Get text, value, attribute, count, URL, title, or element state.",
		topics: ["get", "state", "value", "text"],
	},
	{
		name: "is",
		layer: "verify",
		mutability: "read",
		session: "required",
		description: "Check boolean element/page state.",
		topics: ["is", "visible", "enabled", "checked"],
	},
	{
		name: "find-best",
		layer: "act",
		mutability: "read",
		session: "required",
		description: "Rank semantic intent candidates without executing them.",
		topics: ["semantic", "intent", "candidate"],
	},
	{
		name: "act",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Execute supported semantic intent actions.",
		topics: ["semantic", "intent", "action"],
	},
	{
		name: "analyze-form",
		layer: "observe",
		mutability: "read",
		session: "required",
		description: "Analyze form fields and fillability.",
		topics: ["form", "analyze", "inspect"],
	},
	{
		name: "fill-form",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Fill a form from structured input.",
		topics: ["form", "fill", "json"],
	},
	{
		name: "extract",
		layer: "observe",
		mutability: "read",
		session: "required",
		description: "Extract structured data from current page.",
		topics: ["extract", "data", "structured"],
	},
	{
		name: "check-injection",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Scan page content for prompt-injection risk signals.",
		topics: ["security", "injection", "safety"],
	},
	{
		name: "console",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Inspect renderer console messages.",
		topics: ["console", "logs", "error"],
	},
	{
		name: "network",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Inspect network requests, responses, failures, and bodies.",
		topics: ["network", "request", "response", "api"],
	},
	{
		name: "errors",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Inspect recent page errors.",
		topics: ["errors", "exception", "diagnose"],
	},
	{
		name: "diagnostics",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Digest, export, bundle, and inspect diagnostic signals.",
		topics: ["diagnostics", "digest", "bundle", "evidence", "recovery"],
	},
	{
		name: "trace",
		layer: "diagnose",
		mutability: "mixed",
		session: "required",
		description: "Start, stop, and inspect Playwright traces.",
		topics: ["trace", "evidence", "performance"],
	},
	{
		name: "har",
		layer: "diagnose",
		mutability: "mixed",
		session: "required",
		description: "Record, filter, clean, replay, and inspect HAR artifacts.",
		topics: ["har", "network", "replay", "mock"],
	},
	{
		name: "route",
		layer: "act",
		mutability: "write",
		session: "required",
		description: "Mock, patch, abort, list, or remove network routes.",
		topics: ["route", "mock", "network"],
	},
	{
		name: "sse",
		layer: "diagnose",
		mutability: "read",
		session: "required",
		description: "Observe Server-Sent Events.",
		topics: ["sse", "events", "stream"],
	},
	{
		name: "stream",
		layer: "diagnose",
		mutability: "mixed",
		session: "required",
		description: "Start, stop, or inspect preview stream state.",
		topics: ["stream", "preview", "live"],
	},
	{
		name: "control-state",
		layer: "lifecycle",
		mutability: "read",
		session: "required",
		description: "Inspect human-control ownership state.",
		topics: ["control", "takeover", "human"],
	},
	{
		name: "takeover",
		layer: "lifecycle",
		mutability: "write",
		session: "required",
		description: "Mark session as human-controlled so write operations stop.",
		topics: ["control", "takeover", "human"],
	},
	{
		name: "release-control",
		layer: "lifecycle",
		mutability: "write",
		session: "required",
		description: "Release human-control ownership back to automation.",
		topics: ["control", "release", "human"],
	},
	{
		name: "auth",
		layer: "state",
		mutability: "mixed",
		session: "optional",
		description: "Run built-in auth providers and probes.",
		topics: ["auth", "login", "dc", "admin"],
	},
	{
		name: "state",
		layer: "state",
		mutability: "mixed",
		session: "required",
		description: "Load, save, inspect, and diff browser storage state.",
		topics: ["state", "storage", "cookies", "auth"],
	},
	{
		name: "storage",
		layer: "state",
		mutability: "mixed",
		session: "required",
		description: "Inspect or mutate local/session storage.",
		topics: ["storage", "localStorage", "sessionStorage"],
	},
	{
		name: "cookies",
		layer: "state",
		mutability: "mixed",
		session: "required",
		description: "Inspect or mutate cookies.",
		topics: ["cookies", "auth", "state"],
	},
	{
		name: "profile",
		layer: "state",
		mutability: "mixed",
		session: "optional",
		description: "Manage Chrome profiles and reusable auth/state profiles.",
		topics: ["profile", "chrome", "auth", "state"],
	},
	{
		name: "environment",
		layer: "state",
		mutability: "mixed",
		session: "required",
		description:
			"Control offline mode, geolocation, permissions, clock, domains, bootstrap, and resize.",
		topics: ["environment", "offline", "geolocation", "clock", "permissions"],
	},
	{
		name: "bootstrap",
		layer: "state",
		mutability: "write",
		session: "required",
		description: "Apply init scripts or headers before navigation.",
		topics: ["bootstrap", "init-script", "headers"],
	},
	{
		name: "doctor",
		layer: "meta",
		mutability: "read",
		session: "none",
		description: "Check local environment health and recovery suggestions.",
		topics: ["doctor", "health", "environment", "recovery"],
	},
	{
		name: "skill",
		layer: "meta",
		mutability: "read",
		session: "none",
		description:
			"Show, inspect, and install version-synced pwcli skill content.",
		topics: ["skill", "docs", "workflow"],
	},
	{
		name: "commands",
		layer: "meta",
		mutability: "read",
		session: "none",
		description: "List, search, and route command discovery metadata.",
		topics: ["commands", "discovery", "help", "metadata"],
	},
	{
		name: "dashboard",
		layer: "meta",
		mutability: "mixed",
		session: "optional",
		description: "Open or manage Playwright dashboard helper.",
		topics: ["dashboard", "view", "human"],
	},
	{
		name: "view",
		layer: "meta",
		mutability: "mixed",
		session: "required",
		description: "Open human-visible session view.",
		topics: ["view", "human", "preview"],
	},
	{
		name: "batch",
		layer: "escape",
		mutability: "escape",
		session: "required",
		description: "Run stable structured subset of commands in sequence.",
		topics: ["batch", "escape", "automation"],
	},
	{
		name: "code",
		layer: "escape",
		mutability: "escape",
		session: "required",
		description: "Run short Playwright code snippets as an escape hatch.",
		topics: ["code", "escape", "playwright"],
	},
];

export const commandLayers: CommandLayer[] = [
	"lifecycle",
	"observe",
	"act",
	"verify",
	"diagnose",
	"state",
	"meta",
	"escape",
];
