import type { Command } from "commander";
import { registerAuthCommand } from "./auth.js";
import { registerBatchCommand } from "./batch.js";
import { registerClickCommand } from "./click.js";
import { registerCodeCommand } from "./code.js";
import { registerConnectCommand } from "./connect.js";
import { registerConsoleCommand } from "./console.js";
import { registerDownloadCommand } from "./download.js";
import { registerDragCommand } from "./drag.js";
import { registerFillCommand } from "./fill.js";
import { registerNetworkCommand } from "./network.js";
import { registerOpenCommand } from "./open.js";
import { registerPageCommand } from "./page.js";
import { registerPluginCommand } from "./plugin.js";
import { registerPressCommand } from "./press.js";
import { registerProfileCommand } from "./profile.js";
import { registerReadTextCommand } from "./read-text.js";
import { registerScreenshotCommand } from "./screenshot.js";
import { registerScrollCommand } from "./scroll.js";
import { registerSessionCommand } from "./session.js";
import { registerSkillCommand } from "./skill.js";
import { registerSnapshotCommand } from "./snapshot.js";
import { registerStateCommand } from "./state.js";
import { registerTraceCommand } from "./trace.js";
import { registerTypeCommand } from "./type.js";
import { registerUploadCommand } from "./upload.js";
import { registerWaitCommand } from "./wait.js";

export function registerCommands(program: Command): void {
  registerOpenCommand(program);
  registerConnectCommand(program);
  registerCodeCommand(program);
  registerAuthCommand(program);
  registerBatchCommand(program);
  registerPageCommand(program);
  registerSnapshotCommand(program);
  registerScreenshotCommand(program);
  registerReadTextCommand(program);
  registerFillCommand(program);
  registerTypeCommand(program);
  registerPressCommand(program);
  registerScrollCommand(program);
  registerUploadCommand(program);
  registerDownloadCommand(program);
  registerDragCommand(program);
  registerConsoleCommand(program);
  registerNetworkCommand(program);
  registerClickCommand(program);
  registerWaitCommand(program);
  registerTraceCommand(program);
  registerStateCommand(program);
  registerProfileCommand(program);
  registerSessionCommand(program);
  registerPluginCommand(program);
  registerSkillCommand(program);
}
