import type { Command } from "commander";
import { registerAuthCommand } from "./auth.js";
import { registerBatchCommand } from "./batch.js";
import { registerBootstrapCommand } from "./bootstrap.js";
import { registerCheckCommand } from "./check.js";
import { registerClickCommand } from "./click.js";
import { registerCodeCommand } from "./code.js";
import { registerConsoleCommand } from "./console.js";
import { registerCookiesCommand } from "./cookies.js";
import { registerDashboardCommand } from "./dashboard.js";
import { registerDiagnosticsCommand } from "./diagnostics.js";
import { registerDialogCommand } from "./dialog.js";
import { registerDoctorCommand } from "./doctor.js";
import { registerDownloadCommand } from "./download.js";
import { registerDragCommand } from "./drag.js";
import { registerEnvironmentCommand } from "./environment.js";
import { registerErrorsCommand } from "./errors.js";
import { registerFillCommand } from "./fill.js";
import { registerGetCommand } from "./get.js";
import { registerHarCommand } from "./har.js";
import { registerIsCommand } from "./is.js";
import { registerLocateCommand } from "./locate.js";
import { registerNetworkCommand } from "./network.js";
import { registerObserveCommand } from "./observe.js";
import { registerOpenCommand } from "./open.js";
import { registerPageCommand } from "./page.js";
import { registerPdfCommand } from "./pdf.js";
import { registerPressCommand } from "./press.js";
import { registerProfileCommand } from "./profile.js";
import { registerReadTextCommand } from "./read-text.js";
import { registerResizeCommand } from "./resize.js";
import { registerRouteCommand } from "./route.js";
import { registerScreenshotCommand } from "./screenshot.js";
import { registerScrollCommand } from "./scroll.js";
import { registerSelectCommand } from "./select.js";
import { registerSessionCommand } from "./session.js";
import { registerSkillCommand } from "./skill.js";
import { registerSnapshotCommand } from "./snapshot.js";
import { registerStateCommand } from "./state.js";
import { registerStorageCommand } from "./storage.js";
import { registerTabCommand } from "./tab.js";
import { registerTraceCommand } from "./trace.js";
import { registerTypeCommand } from "./type.js";
import { registerUncheckCommand } from "./uncheck.js";
import { registerUploadCommand } from "./upload.js";
import { registerVerifyCommand } from "./verify.js";
import { registerWaitCommand } from "./wait.js";

export function registerCommands(program: Command): void {
  registerOpenCommand(program);
  registerCodeCommand(program);
  registerAuthCommand(program);
  registerBatchCommand(program);
  registerBootstrapCommand(program);
  registerDashboardCommand(program);
  registerDiagnosticsCommand(program);
  registerDialogCommand(program);
  registerDoctorCommand(program);
  registerEnvironmentCommand(program);
  registerErrorsCommand(program);
  registerPageCommand(program);
  registerPdfCommand(program);
  registerResizeCommand(program);
  registerSnapshotCommand(program);
  registerScreenshotCommand(program);
  registerReadTextCommand(program);
  registerCheckCommand(program);
  registerLocateCommand(program);
  registerGetCommand(program);
  registerIsCommand(program);
  registerVerifyCommand(program);
  registerFillCommand(program);
  registerTypeCommand(program);
  registerPressCommand(program);
  registerScrollCommand(program);
  registerSelectCommand(program);
  registerUncheckCommand(program);
  registerUploadCommand(program);
  registerDownloadCommand(program);
  registerDragCommand(program);
  registerConsoleCommand(program);
  registerHarCommand(program);
  registerNetworkCommand(program);
  registerObserveCommand(program);
  registerClickCommand(program);
  registerRouteCommand(program);
  registerWaitCommand(program);
  registerTraceCommand(program);
  registerCookiesCommand(program);
  registerStateCommand(program);
  registerStorageCommand(program);
  registerProfileCommand(program);
  registerTabCommand(program);
  registerSessionCommand(program);
  registerSkillCommand(program);
}
