import type { Command } from "commander";
import {
  managedStateDiff,
  managedStateLoad,
  managedStateSave,
} from "../../domain/identity-state/service.js";
import { printCommandError, printCommandResult } from "../output.js";
import {
  addSessionOption,
  printSessionAwareCommandError,
  requireSessionName,
} from "./session-options.js";

export function registerStateCommand(program: Command): void {
  addSessionOption(
    program
      .command("state <action> [file]")
      .description("Save, load, or diff browser state for a managed session"),
  )
    .option("--before <file>", "State diff baseline snapshot file")
    .option("--after <file>", "Optional state diff after snapshot file")
    .action(async (
      action: string,
      file: string | undefined,
      options: { session?: string; before?: string; after?: string },
      command: Command,
    ) => {
      try {
        if (action === "diff") {
          const before = options.before ?? file;
          const hasSession = Boolean(command.optsWithGlobals<{ session?: string }>().session ?? options.session);
          const sessionName = hasSession ? requireSessionName(options, command) : undefined;
          printCommandResult(
            "state diff",
            await managedStateDiff({
              sessionName,
              before,
              after: options.after,
            }),
          );
          return;
        }
        const sessionName = requireSessionName(options, command);
        if (action === "save") {
          printCommandResult("state save", await managedStateSave(file, { sessionName }));
          return;
        }
        if (action === "load" && file) {
          printCommandResult("state load", await managedStateLoad(file, { sessionName }));
          return;
        }
        throw new Error("state requires `save [file]`, `load <file>`, or `diff --before <file>`");
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        if (message === "STATE_DIFF_BEFORE_REQUIRED") {
          printCommandError("state diff", {
            code: "STATE_DIFF_BEFORE_REQUIRED",
            message: "state diff requires a baseline snapshot file",
            suggestions: [
              "Run `pw state diff --session bug-a --before .pwcli/state/bug-a-before.json` to capture a baseline snapshot",
              "Later rerun the same command after state changes to compare against the saved baseline",
              "Or compare two saved snapshot files with `pw state diff --before before.json --after after.json`",
            ],
          });
          process.exitCode = 1;
          return;
        }
        if (message === "STATE_DIFF_AFTER_REQUIRED") {
          printCommandError("state diff", {
            code: "STATE_DIFF_AFTER_REQUIRED",
            message: "state diff without a session requires both --before and --after snapshot files",
            suggestions: [
              "Run `pw state diff --before before.json --after after.json` to compare two saved snapshots",
              "Or add `--session <name>` so pwcli can capture the current after snapshot read-only",
            ],
          });
          process.exitCode = 1;
          return;
        }
        if (message === "STATE_DIFF_SNAPSHOT_INVALID") {
          printCommandError("state diff", {
            code: "STATE_DIFF_SNAPSHOT_INVALID",
            message: "state diff snapshot file is missing or invalid",
            suggestions: [
              "Recreate the baseline with `pw state diff --session bug-a --before before.json`",
              "Only compare files previously generated by `pw state diff`",
            ],
          });
          process.exitCode = 1;
          return;
        }
        printSessionAwareCommandError("state", error, {
          code: "STATE_FAILED",
          message: "state failed",
          suggestions: [
            "Use `pw state --session bug-a save auth.json` or `pw state --session bug-a load auth.json`",
            "Use `pw state diff --session bug-a --before before.json` for read-only state comparison",
          ],
        });
        process.exitCode = 1;
      }
    });
}
