import { defineCommand } from "citty";
import { managedEnvironmentClockInstall, managedEnvironmentClockResume, managedEnvironmentClockSet, managedEnvironmentGeolocationSet, managedEnvironmentOffline, managedEnvironmentPermissionsClear, managedEnvironmentPermissionsGrant } from "#engine/environment.js";
import { sharedArgs } from "#cli/args.js";
import { firstPos, num, positionals, print, session, withCliError, type CliArgs } from "./_helpers.js";

const offline = defineCommand({ meta: { name: "offline", description: "Set network offline mode" }, args: sharedArgs, async run({ args }) { const a = args as CliArgs; try { print("environment offline", await managedEnvironmentOffline(firstPos(a) as "on" | "off", { sessionName: session(a) }), a); } catch (e) { withCliError("environment offline", a, e); } } });
const geoSet = defineCommand({ meta: { name: "set", description: "Set geolocation" }, args: { ...sharedArgs, accuracy: { type: "string", description: "Accuracy meters", valueHint: "m" } }, async run({ args }) { const a = args as CliArgs; try { const p = positionals(a); print("environment geolocation set", await managedEnvironmentGeolocationSet({ sessionName: session(a), latitude: num(p[0]) as number, longitude: num(p[1]) as number, accuracy: num(a.accuracy) }), a); } catch (e) { withCliError("environment geolocation set", a, e); } } });
const permGrant = defineCommand({ meta: { name: "grant", description: "Grant permissions" }, args: sharedArgs, async run({ args }) { const a = args as CliArgs; try { print("environment permissions grant", await managedEnvironmentPermissionsGrant({ sessionName: session(a), permissions: positionals(a) }), a); } catch (e) { withCliError("environment permissions grant", a, e); } } });
const permClear = defineCommand({ meta: { name: "clear", description: "Clear permissions" }, args: sharedArgs, async run({ args }) { const a = args as CliArgs; try { print("environment permissions clear", await managedEnvironmentPermissionsClear({ sessionName: session(a) }), a); } catch (e) { withCliError("environment permissions clear", a, e); } } });
const clockInstall = defineCommand({ meta: { name: "install", description: "Install fake clock" }, args: sharedArgs, async run({ args }) { const a = args as CliArgs; try { print("environment clock install", await managedEnvironmentClockInstall({ sessionName: session(a) }), a); } catch (e) { withCliError("environment clock install", a, e); } } });
const clockSet = defineCommand({ meta: { name: "set", description: "Set fake clock time" }, args: sharedArgs, async run({ args }) { const a = args as CliArgs; try { print("environment clock set", await managedEnvironmentClockSet(new Date(firstPos(a) as string).toISOString(), { sessionName: session(a) }), a); } catch (e) { withCliError("environment clock set", a, e); } } });
const clockResume = defineCommand({ meta: { name: "resume", description: "Resume clock" }, args: sharedArgs, async run({ args }) { const a = args as CliArgs; try { print("environment clock resume", await managedEnvironmentClockResume({ sessionName: session(a) }), a); } catch (e) { withCliError("environment clock resume", a, e); } } });

export default defineCommand({ meta: { name: "environment", description: "Environment and clock controls" }, subCommands: { offline, geolocation: defineCommand({ meta: { name: "geolocation", description: "Geolocation controls" }, subCommands: { set: geoSet } }), permissions: defineCommand({ meta: { name: "permissions", description: "Permission controls" }, subCommands: { grant: permGrant, clear: permClear } }), clock: defineCommand({ meta: { name: "clock", description: "Clock controls" }, subCommands: { install: clockInstall, set: clockSet, resume: clockResume } }) } });
