export default {
  snapshot: () => import("./snapshot.js"),
  "read-text": () => import("./read-text.js"),
  text: () => import("./read-text.js"),
  status: () => import("./status.js"),
  observe: () => import("./status.js"),
  screenshot: () => import("./screenshot.js"),
  pdf: () => import("./pdf.js"),
  accessibility: () => import("./accessibility.js"),

  page: () => import("./page.js"),
  tab: () => import("./tab.js"),

  click: () => import("./click.js"),
  fill: () => import("./fill.js"),
  type: () => import("./type.js"),
  press: () => import("./press.js"),
  hover: () => import("./hover.js"),
  check: () => import("./check.js"),
  uncheck: () => import("./uncheck.js"),
  select: () => import("./select.js"),
  drag: () => import("./drag.js"),
  upload: () => import("./upload.js"),
  download: () => import("./download.js"),

  scroll: () => import("./scroll.js"),
  resize: () => import("./resize.js"),
  mouse: () => import("./mouse.js"),
  dialog: () => import("./dialog.js"),
  open: () => import("./open.js"),

  locate: () => import("./locate.js"),
  get: () => import("./get.js"),
  is: () => import("./is.js"),
  verify: () => import("./verify.js"),
  wait: () => import("./wait.js"),

  console: () => import("./console.js"),
  network: () => import("./network.js"),
  errors: () => import("./errors.js"),
  diagnostics: () => import("./diagnostics.js"),
  trace: () => import("./trace.js"),
  har: () => import("./har.js"),
  route: () => import("./route.js"),
  sse: () => import("./sse.js"),

  auth: () => import("./auth.js"),
  state: () => import("./state.js"),
  storage: () => import("./storage.js"),
  cookies: () => import("./cookies.js"),

  session: () => import("./session.js"),

  profile: () => import("./profile.js"),
  environment: () => import("./environment.js"),
  doctor: () => import("./doctor.js"),
  bootstrap: () => import("./bootstrap.js"),
  batch: () => import("./batch.js"),
  code: () => import("./code.js"),
  video: () => import("./video.js"),
  skill: () => import("./skill.js"),
  dashboard: () => import("./dashboard.js"),
} as const;
